applications:
  - application: darwin-ofs-v2
    base-path: feature-store
    path: app
    base-image: darwin/java:11-maven-bookworm-slim
    enabled: false
    env:
      - name: VAULT_SERVICE_MYSQL_USERNAME
        value: "dummy"
      - name: VAULT_SERVICE_MYSQL_PASSWORD
        value: "dummy"
      - name: DARWIN_FEATURE_STORE_HOST
        value: "darwin-feature-store"
      - name: DARWIN_FEATURE_STORE_ADMIN_HOST
        value: "darwin-feature-store-admin"
      - name: AWS_ENDPOINT_OVERRIDE
        value: "http://darwin-localstack:4566"

  - application: darwin-ofs-v2-admin
    base-path: feature-store
    path: admin
    base-image: darwin/java:11-maven-bookworm-slim
    enabled: false
    env:
      - name: VAULT_SERVICE_MYSQL_USERNAME
        value: "dummy"
      - name: VAULT_SERVICE_MYSQL_PASSWORD
        value: "dummy"
      - name: DARWIN_FEATURE_STORE_HOST
        value: "darwin-feature-store"
      - name: DARWIN_FEATURE_STORE_ADMIN_HOST
        value: "darwin-feature-store-admin"
      - name: AWS_ENDPOINT_OVERRIDE
        value: "http://darwin-localstack:4566"

  - application: darwin-ofs-v2-consumer
    base-path: feature-store
    path: consumer
    base-image: darwin/java:11-maven-bookworm-slim
    enabled: false
    env:
      - name: VAULT_SERVICE_MYSQL_USERNAME
        value: "dummy"
      - name: VAULT_SERVICE_MYSQL_PASSWORD
        value: "dummy"
      - name: DARWIN_FEATURE_STORE_HOST
        value: "darwin-feature-store"
      - name: DARWIN_FEATURE_STORE_ADMIN_HOST
        value: "darwin-feature-store-admin"
      - name: AWS_ENDPOINT_OVERRIDE
        value: "http://darwin-localstack:4566"

  - application: darwin-mlflow
    base-path: mlflow
    path: .
    base-image: darwin/python:3.9.7-pip-bookworm-slim
    enabled: true
    env:
      - name: VAULT_SERVICE_MLFLOW_ADMIN_USERNAME
        value: "admin"
      - name: VAULT_SERVICE_MLFLOW_ADMIN_PASSWORD
        value: "password"
      - name: CONFIG_SERVICE_MYSQL_DATABASE
        value: "darwin_mlflow"
      - name: TEAM_SUFFIX
        value: "-darwin-local"
      - name: VPC_SUFFIX
        value: "-darwin-local"
      - name: VAULT_SERVICE_MYSQL_USERNAME
        value: "root"
      - name: VAULT_SERVICE_MYSQL_PASSWORD
        value: "password"
      - name: CONFIG_SERVICE_S3_PATH
        value: "s3://darwin-mlflow-bucket"

  - application: darwin-mlflow-app
    base-path: mlflow
    path: .
    base-image: darwin/python:3.9.7-pip-bookworm-slim
    enabled: true
    env:
      - name: VAULT_SERVICE_MLFLOW_ADMIN_USERNAME
        value: "admin"
      - name: VAULT_SERVICE_MLFLOW_ADMIN_PASSWORD
        value: "password"
      - name: CONFIG_SERVICE_MYSQL_DATABASE
        value: "darwin_mlflow"
      - name: TEAM_SUFFIX
        value: "-darwin-local"
      - name: VPC_SUFFIX
        value: "-darwin-local"
      - name: VAULT_SERVICE_MYSQL_USERNAME
        value: "root"
      - name: VAULT_SERVICE_MYSQL_PASSWORD
        value: "password"
      - name: CONFIG_SERVICE_S3_PATH
        value: "s3://darwin-mlflow-bucket"

  - application: chronos
    base-path: chronos
    path: .
    base-image: darwin/python:3.9.7-pip-bookworm-slim
    enabled: false
    env: []

  - application: chronos-consumer
    base-path: chronos
    path: .
    base-image: darwin/python:3.9.7-pip-bookworm-slim
    enabled: false
    env: []

  - application: darwin-compute
    base-path: darwin-compute
    path: .
    base-image: darwin/python:3.9.7-pip-bookworm-slim
    enabled: true
    env: []

  - application: darwin-cluster-manager
    base-path: darwin-cluster-manager
    path: .
    base-image: darwin/golang:1.18-bookworm-slim
    enabled: true
    env: []

  - application: darwin-workspace
    base-path: workspace
    path: .
    base-image: darwin/python:3.9.7-pip-bookworm-slim
    enabled: false
    env: []

  - application: ml-serve-app
    base-path: ml-serve-app
    path: .
    base-image: darwin/python:3.9.7-pip-bookworm-slim
    enabled: true
    env: []

  - application: artifact-builder
    base-path: artifact-builder
    path: .
    base-image: darwin/python:3.9.7-pip-bookworm-slim
    enabled: true
    env: []

  - application: darwin-catalog
    base-path: darwin-catalog
    path: .
    base-image: darwin/java:11-maven-bookworm-slim
    enabled: true
    env:
      - name: LOAD_TEST_DATA
        value: "true"

  - application: ml-platform-graphql
    base-path: ml-platform-graphql
    path: .
    base-image: darwin/nodejs:20.16.0-bookworm-slim
    enabled: true
    env:
      - name: ENV
        value: "local"
      - name: SERVICE_NAME
        value: "ml-platform-graphql"
      - name: NAMESPACE
        value: "darwin"
      - name: DEPLOYMENT_TYPE
        value: "container"
      - name: NODE_ENV
        value: "production"
      - name: PORT
        value: "4000"

  - application: ml-platform-mf
    base-path: ml-platform-mf
    path: .
    base-image: darwin/nodejs:20.16.0-bookworm-slim
    enabled: true
    env:
      - name: ENV
        value: "local"
      - name: SERVICE_NAME
        value: "ml-platform-mf"
      - name: NAMESPACE
        value: "darwin"
      - name: DEPLOYMENT_TYPE
        value: "container"
      - name: NODE_ENV
        value: "dev-local"
      - name: PORT
        value: "7700"
      - name: GRAPHQL_URL
        value: "http://localhost/ml-platform/graphql"
      - name: ML_PLATFORM_GRAPHQL_SERVICE
        value: "http://darwin-ml-platform-graphql:4000/graphql"

ray-images:
  - image-name: ray:2.37.0
    dockerfile-path: darwin-compute/runtimes/cpu/New-Lightweight/Ray2.37_Py3.10
    registry: localhost:5000

serve-images:
  - image-name: serve-md-runtime:latest
    dockerfile-path: ml-serve-app/runtime/darwin-serve-runtime
    registry: localhost:5000

datastores:
  - name: mysql
    image: mysql
    tag: "8.0"
    enabled: true
  - name: cassandra
    image: cassandra
    tag: "5.0"
    enabled: false
  - name: kafka
    image: confluentinc/cp-kafka
    tag: "7.4.0"
    enabled: false
  - name: zookeeper
    image: zookeeper
    tag: "3.8"
    enabled: false
  - name: airflow
    image: apache/airflow
    tag: "2.7.0"
    enabled: false
  - name: rabbitmq
    image: rabbitmq
    tag: "3.12-management-alpine"
    enabled: false
  - name: localstack
    image: localstack/localstack
    tag: "latest"
    enabled: true
  - name: opensearch
    image: opensearchproject/opensearch
    tag: "2.11.0"
    enabled: true
  - name: busybox
    image: busybox
    tag: "1.36"
    enabled: true

operators:
  - name: kuberay-operator
    image: quay.io/kuberay/operator
    tag: "v1.1.0"
    enabled: true
  - name: nginx
    image: nginx
    tag: "1.27.4"
    enabled: true
  - name: grafana
    image: grafana/grafana
    tag: "latest"
    enabled: true
  - name: curl
    image: curlimages/curl
    tag: "latest"
    enabled: true
  - name: alpine-k8s
    image: alpine/k8s
    tag: "1.28.0"
    enabled: true
